apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb-service
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
              name: web
          env:
            - name: MONG0_INITDB_ROOT_USERNAME
              value: 'mongoadmin'
            - name: MONG0_INITDB_ROOT_PASSWORD
              # kubectl create secret generic catalog-secrets --from-literal=mongodb-password='Pass#word1'
              valueFrom:
                secretKeyRef:
                  name: catalog-secrets
                  key: mongodb-password
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data # must match with volumeMounts -> name
      spec:
        accessModes: ['ReadWriteOnce'] # ReadWriteOnce means one node can read and write to it at a time
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
